# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 1
  - name: About
    url: /about/
    weight: 2
  - name: AI Mapping
    url: /ai_mapping/
    weight: 3
  - name: Topo Surveying
    url: /topo_surveying/
    weight: 4
  - name: Education & Training
    url: /training/
    weight: 5
