# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 1
  - name: About
    url: /about/
    weight: 2
  - name: Aerial Mapping
    url: /#solutions
    weight: 3
  - name: Data Analytics
    url: blog/
    weight: 4
  - name: Training
    url: blog/
    weight: 5
